### ISSUE TITLE
Pre-commit hook never finishes with `pnpm run` command

### ISSUE THREAD

**Issue by dkzlv** [evilmartians/lefthook#535]
### :wrench: Summary

See title

### Lefthook version

`1.4.8 5d656f934507c221742509e79c65b1b77490f4a7`

### Steps to reproduce

[`@nanostores/query` repo](https://github.com/nanostores/query), main branch.

If I run `pnpm test` from console, it finishes in ~7s.

```
➜  nanoquery git:(main) time pnpm test
... lots of logs
pnpm test  7.39s user 1.09s system 267% cpu 3.169 total
```

Then try to change something and trigger pre-commit hook.

### Expected results

It hangs indefinitely and never resolves.

### Actual results

It should!

### Logs / Screenshots

Here's a video repro.

https://github.com/evilmartians/lefthook/assets/2846746/47679a01-1cef-4af9-8d98-0c3a40b7d20c

**Comment by dkzlv** [comment]
It was something related to `size-limit`. When I added `--silent` flag to it, all worked fine. I guess, I'll leave it opened, maybe it will be something of interest for you.

**Comment by mrexox** [comment]
Hey! Thank you for the issue. Unfortunately I can't setup the project, it fails to find `dist/nanoquery.umd.cjs`

```bash
$ pnpm test

> @nanostores/query@0.2.4 test /tmp/query
> pnpm run /^test:/

. test:types$ tsc --noEmit && vitest typecheck --run
└─ Running...
. test:unit$ vitest run
└─ Running...
. test:size$ size-limit
│  ERROR  Error: Cannot find module '/tmp/query/dist/nanoquery.umd.cjs'
│ Require stack:
│ - /tmp/query/node_modules/.pnpm/size-limit@8.2.6/node_modules/size-limit/get-config.js
│ - /tmp/query/node_modules/.pnpm/size-limit@8.2.6/node_modules/size-limit/run.js
│ - /tmp/query/node_modules/.pnpm/size-limit@8.2.6/node_modules/size-limit/bin.js
│     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
│     at Function.resolve (node:internal/modules/cjs/helpers:108:19)
│     at /tmp/query/node_modules/.pnpm/size-limit@8.2.6/node_modules/size-limit/get-config.js:135:23
│     at Array.map (<anonymous>)
│     at getConfig (/tmp/query/node_modules/.pnpm/size-limit@8.2.6/node_modules/size-limit/get-config.js:128:21)
│     at async module.exports (/tmp/query/node_modules/.pnpm/size-limit@8.2.6/node_modules/size-limit/run.js:74:14)
└─ Failed in 157ms at /tmp/query
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Test failed. See above for more details.
```

Not sure why this happens. I've run only `pnpm install` before `pnpm test`

I hope I'll be able to find the issue if I succeed with the project setup. Could you help me?

**Comment by mrexox** [comment]
I'm closing this issue because of no response. I hope that the bug doesn't reproduce any more. If it does, feel free to re-open.
