### ISSUE TITLE
1.5.2: panic: runtime error: index out of range [2] with length 2

### ISSUE THREAD

**Issue by blampe** [evilmartians/lefthook#565]
### Lefthook version

1.5.2

### Steps to reproduce

`tools/bin/lefthook run pre-commit --no-tty`

### Actual results

```
panic: runtime error: index out of range [2] with length 2

goroutine 24 [running]:
github.com/muesli/termenv.xTermColor({0x1400023c4b0, 0x18})
	.../vendor/github.com/muesli/termenv/color.go:139 +0x328
github.com/muesli/termenv.Output.backgroundColor({0x0, {0x1009375f8, 0x14000052040}, {0x1009389a0, 0x100c0c620}, 0x0, 0x0, 0x0, 0x14000010b80, {0x100937898, ...}, ...})
	.../vendor/github.com/muesli/termenv/termenv_unix.go:93 +0x98
github.com/muesli/termenv.(*Output).BackgroundColor.func1()
	.../vendor/github.com/muesli/termenv/output.go:162 +0x88
github.com/muesli/termenv.(*Output).BackgroundColor(0x140000783c0)
	.../vendor/github.com/muesli/termenv/output.go:168 +0x64
github.com/muesli/termenv.(*Output).HasDarkBackground(0x14000244458?)
	.../vendor/github.com/muesli/termenv/output.go:176 +0x1c
github.com/charmbracelet/lipgloss.(*Renderer).HasDarkBackground(...)
	.../vendor/github.com/charmbracelet/lipgloss/renderer.go:116
github.com/charmbracelet/lipgloss.AdaptiveColor.color({{0x1007f5976?, 0x1007b2614?}, {0x1007f597d?, 0x100da4a68?}}, 0x100bccd90)
	.../vendor/github.com/charmbracelet/lipgloss/color.go:100 +0x4c
github.com/charmbracelet/lipgloss.Style.styleBorder({0x100bccd90?, 0x140002289f0?, {0x0?, 0x1?}}, {0x140002387cc, 0x3}, {0x100938568?, 0x100bc2620}, {0x1009384f0?, 0x100c0c620})
	.../vendor/github.com/charmbracelet/lipgloss/borders.go:387 +0x174
github.com/charmbracelet/lipgloss.Style.applyBorder({0x100bccd90?, 0x140002289f0?, {0x0?, 0x0?}}, {0x0, 0x0})
	.../vendor/github.com/charmbracelet/lipgloss/borders.go:320 +0xbec
github.com/charmbracelet/lipgloss.Style.Render({0x100bccd90?, 0x140002289f0?, {0x0?, 0x0?}}, {0x14000245338?, 0x10051b4c0?, 0x14000245378?})
	.../vendor/github.com/charmbracelet/lipgloss/style.go:376 +0x1fd8
github.com/evilmartians/lefthook/internal/log.(*Logger).Debug(0x1400002c640, {0x14000245508, 0x1, 0x10?})
	.../vendor/github.com/evilmartians/lefthook/internal/log/log.go:334 +0x1cc
github.com/evilmartians/lefthook/internal/log.Debug({0x140002455c8?, 0x1f?, 0x140002280a0?})
	.../vendor/github.com/evilmartians/lefthook/internal/log/log.go:126 +0x1ac
github.com/evilmartians/lefthook/internal/git.(*OsExec).rawExecArgs(0x1400002a890, {0x14000228090, 0x3, 0x3})
	.../vendor/github.com/evilmartians/lefthook/internal/git/exec.go:84 +0x280
github.com/evilmartians/lefthook/internal/git.(*OsExec).RawCmd(0x14000226040?, {0x1008084db, 0x30})
	.../vendor/github.com/evilmartians/lefthook/internal/git/exec.go:69 +0x94
github.com/evilmartians/lefthook/internal/git.(*OsExec).CmdLines(0x20?, {0x1008084db?, 0x14000226040?})
	.../vendor/github.com/evilmartians/lefthook/internal/git/exec.go:42 +0x20
github.com/evilmartians/lefthook/internal/git.(*Repository).FilesByCommand(0x140000a6380, {0x1008084db?, 0x1?})
	.../vendor/github.com/evilmartians/lefthook/internal/git/repository.go:292 +0x34
github.com/evilmartians/lefthook/internal/git.(*Repository).StagedFiles(...)
	.../vendor/github.com/evilmartians/lefthook/internal/git/repository.go:97
github.com/evilmartians/lefthook/internal/lefthook/run.(*Runner).buildRun(0x140000de4d0, 0x140000de160)
	.../vendor/github.com/evilmartians/lefthook/internal/lefthook/run/prepare_command.go:106 +0x4a4
github.com/evilmartians/lefthook/internal/lefthook/run.(*Runner).prepareCommand(0x140000de4d0, {0x1400009bae8, 0xe}, 0x140000de160)
	.../vendor/github.com/evilmartians/lefthook/internal/lefthook/run/prepare_command.go:55 +0x3cc
github.com/evilmartians/lefthook/internal/lefthook/run.(*Runner).runCommand(0x140000de4d0, {0x1009397f0, 0x140002fb080}, {0x1400009bae8, 0xe}, 0x140000de160)
	.../vendor/github.com/evilmartians/lefthook/internal/lefthook/run/runner.go:375 +0x50
github.com/evilmartians/lefthook/internal/lefthook/run.(*Runner).runCommands.func1({0x1400009bae8?, 0x10056f694?}, 0x0?)
	.../vendor/github.com/evilmartians/lefthook/internal/lefthook/run/runner.go:355 +0x74
created by github.com/evilmartians/lefthook/internal/lefthook/run.(*Runner).runCommands in goroutine 22
	.../vendor/github.com/evilmartians/lefthook/internal/lefthook/run/runner.go:353 +0x478
```

### Logs / Screenshots

```bash
LEFTHOOK_VERBOSE=true git ...
```

**Comment by mrexox** [comment]
@blampe , thank you for the issue report. Looks like a bug in lefthook dependency. Can you provide some more context, like config file, the OS and terminal emulator you use?

**Comment by mrexox** [comment]
Closing this since color mangement has changed and no feedback received.
